---
ID: "42745ceb-1ced-4996-a084-5b16a2c18a06"
Parent: "d372a588-32fb-457f-b3dc-734abf88ed9b"
Template: "d372a588-32fb-457f-b3dc-734abf88ed9b"
Path: /sitecore/templates/Feature/Search/Rendering Parameters/Search Paging Parameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200117T125815Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
